---
# handlers file for ansible-role-zabbixserver
- name: start zabbix-server
  service: name=zabbix-server state=started

- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart php5-fpm 
  become: yes
  service: name=php5-fpm state=restarted


